### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by ascherer** [ascherer/mmix#15]
* https://github.com/ascherer/mmix/blob/b32eba19f7af1ed0ca66ce14f4e09cc074b2eef5/mmix-config.w#L212 should be **simultaneously**. [Page 112.]

* https://github.com/ascherer/mmix/blob/b32eba19f7af1ed0ca66ce14f4e09cc074b2eef5/mmix-sim.w#L250 should add an **it**. [Page 336.]

* The ternary conditional operator `?:` is formatted inconsistently for `Fopen` and `Fseek` in section **4** of `mmix-sim.w`, i.e., there are several spaces (`\ `) missing. [Pages 336 and 338 resp.]

* Also in section **4** of `mmix-sim.w`, purge two commas in displayed lines for `Fopen` and `Fputs`. [Pages 336 and 337 resp.]

* The **tricky sequence** in section **6** of `mmix-sim.w` should purge two extra spaces after commas. [Page 339.]

* ~~Section **59** of `mmix-sim.w`: **list of lists** and **built into**.~~ This was DEK's intention. [Page 361.]

* `@d rQ 16` in section **12** of `mmmix.w` repeats the same line form `mmix-pipe.h`. [Page 500.]

**Comment by david-solomon-henshaw** [comment]
Good day please i'd like to fix this issue as my way of getting into open source contribution, can fixing of this typos be assigned to me ?

**Comment by ascherer** [comment]
I've just committed fixes to the items listed. More "typos" might be added later. Feel free to clone this project and submit "pull requests"; no formal "assignment" is necessary.

**Comment by ascherer** [comment]
Also issue #22 is a typo.

**Comment by ascherer** [comment]
In section 18 of `mmixal.w` the two instructions `sp GREG 0;` and `fp GREG 0` should be separated by a space; see section 16 for a similar case.
